### ISSUE TITLE
How to import to Android-Studio?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [carlemil/BlurredBackgroundViewDemo#1]
it seems it's for Ecilpse only...

**Comment by carlemil** [comment]
It is, never built it with android studio since the support was near to non existent when i was working on it.

**Comment by AndroidDeveloperLB** [comment]
@carlemil  Can you please make it work for Android Studio ?

**Comment by carlemil** [comment]
No, if you want to fork it or submit a patch to get it up to date and working with gradle/studio i will be happy to accept such a contribution, but i don't have the time or knowledge to do it myself.
